local export = require("review.export")
local config = require("review.config")

describe("review tmux", function()
  describe("_tmux_target_of", function()
    it("maps the next-pane label to +", function()
      assert.equal("+", export._tmux_target_of("+ (next pane)"))
      assert.equal("+", export._tmux_target_of("+"))
    end)

    it("extracts window.pane index from a list-panes line", function()
      assert.equal("1.0", export._tmux_target_of("1.0: nvim [editor]"))
      assert.equal("2.3", export._tmux_target_of("2.3: bash [shell]"))
    end)

    it("passes through an explicit target unchanged", function()
      assert.equal("mysession:1.2", export._tmux_target_of("mysession:1.2"))
    end)
  end)

  describe("config defaults", function()
    it("ships a tmux block and a T keymap", function()
      config.setup({})
      local cfg = config.get()
      assert.equal("T", cfg.keymaps.send_tmux)
      assert.is_false(cfg.tmux.send_enter)
      assert.same({ "+" }, cfg.tmux.panes)
      assert.same({}, cfg.tmux.auto_select_panes)
    end)
  end)
end)
